# Generated by Django 4.1 on 2022-11-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumrut', models.CharField(max_length=12)),
                ('alumnombre', models.CharField(max_length=15)),
                ('alumapaterno', models.CharField(max_length=15)),
                ('alumamaterno', models.CharField(max_length=15)),
                ('alumdireccion', models.CharField(max_length=60)),
                ('alumemail', models.CharField(max_length=40)),
                ('alumfono', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciucodigo', models.IntegerField()),
                ('ciunombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipocurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipcurcodigo', models.IntegerField()),
                ('tipcurnombre', models.CharField(max_length=20)),
                ('tipcurvalor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usulogin', models.CharField(max_length=15)),
                ('usupassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succodigo', models.IntegerField()),
                ('ciucodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matnumero', models.IntegerField()),
                ('matfecha', models.DateField()),
                ('alumrut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumnos')),
                ('succodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sucursales')),
                ('tipcurcodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipocurso')),
            ],
        ),
    ]
