# Generated by Django 4.1 on 2022-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='sucnombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
