# Generated by Django 4.1 on 2022-11-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sucursales_sucnombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matfecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('ciudadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciudad')),
            ],
        ),
        migrations.RemoveField(
            model_name='matriculas',
            name='alumrut',
        ),
        migrations.RemoveField(
            model_name='matriculas',
            name='succodigo',
        ),
        migrations.RemoveField(
            model_name='matriculas',
            name='tipcurcodigo',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='ciucodigo',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumamaterno',
            new_name='amaterno',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumapaterno',
            new_name='apaterno',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumdireccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumfono',
            new_name='fono',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumnombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='alumrut',
            new_name='rut',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='tipcurnombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='tipcurcodigo',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usulogin',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usupassword',
            new_name='psw',
        ),
        migrations.RemoveField(
            model_name='tipocurso',
            name='tipcurvalor',
        ),
        migrations.DeleteModel(
            name='ciudades',
        ),
        migrations.DeleteModel(
            name='matriculas',
        ),
        migrations.DeleteModel(
            name='sucursales',
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumrut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumnos'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='sucursalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sucursal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipcurcodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipocurso'),
        ),
    ]
