# Generated by Django 4.1 on 2022-11-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_alumnos_fono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='login',
            new_name='username',
        ),
    ]
