# Generated by Django 4.1 on 2022-12-01 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_login_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='alumrut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.alumnos'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='sucursalId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.sucursal'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipcurcodigo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipocurso'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
