# Generated by Django 4.1 on 2022-12-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_matricula_alumrut_alter_matricula_sucursalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='alumrut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.alumnos'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='sucursalId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sucursal'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipcurcodigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipocurso'),
        ),
    ]
