# Generated by Django 4.1 on 2022-12-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_matricula_alumrut_alter_matricula_sucursalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
