# Generated by Django 4.1 on 2022-12-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_sucursal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ciudadId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ciudad'),
        ),
    ]
