# Generated by Django 4.1 on 2022-12-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_sucursal_ciudadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ciudadId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciudad'),
        ),
    ]
